### ISSUE TITLE
Steam game search method

### ISSUE THREAD

**Issue by Dontcampy** [l19980623/SteamKeyManager#6]
Valve didn't give the search api in https://developer.valvesoftware.com/wiki/Steam_Web_API.
so I analyze the store.steampowered.com. Maybe this method can help you make some new functions. 
Example:　http://store.steampowered.com/search/suggest?term=cs&f=games&cc=CN&l=chinese&no_violence=0&no_sex=0&v=3134287

## Arguments: 

- term: Search key
- f: I don't really know what it is. Maybe the store navigation values, but if i change it value, the server will not return items' icons and links in the response.
- cc: The shop's location.
- l: Language.
- no_violence: Such as its name.
- no_sex: Such as its name.
- v: Version. It's unnecessary.

**Comment by kazum1kun** [comment]
This QoL improvement will not be implemented till later. Ty for the suggestion

**Comment by kazum1kun** [comment]
This function is now fully functional with Release 0.2.1
