### ISSUE TITLE
GUI部件显示不正常

### ISSUE THREAD

**Issue by Dontcampy** [l19980623/SteamKeyManager#7]
任何语言下均无法正常显示Button的文本。
![5lf 0dkc9r e im jq6yih3](https://user-images.githubusercontent.com/5778698/27815789-8623e8d8-60b9-11e7-8c86-303f37b50e58.png)

系统信息：
Windows 10（64 位）
主显示分辨率：1920 x 1080
桌面分辨率：1920 x 1080
主显示大小：13.54" x 7.64"（尺寸 15.51"）
125%缩放

**Comment by kazum1kun** [comment]
I tested and the button shows on 100% DPI and 300% DPI so the issue should be specific to some DPI level. I will look into that on later stage of development.

**Comment by kazum1kun** [comment]
Development ceased on this project. Please see [QSteamKeyManager](https://github.com/l19980623/QSteamKeyManager) for the next-generation SKM.
