### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by azumukupoe** [l19980623/SteamKeyManager#8]

**Comment by kazum1kun** [comment]
Thanks for the report. Can you explain the issue with further details? Include things like your JRE version, your OS, and the steps leading to this problem. Thanks!

**Comment by kazum1kun** [comment]
Development ceased on this project. Please see [QSteamKeyManager](https://github.com/l19980623/QSteamKeyManager) for the next-generation SKM.
